#!/bin/sh
exit
dev=/dev/hda4

umount $dev
mkfs.ext2 $dev
mount $dev /convertfs
#cp -a /boot /convertfs
#cp -a /documents/hardware /convertfs
cp -a /var /convertfs
cp -a /doc /convertfs
cp -a /sbin /convertfs
umount $dev
